### PR TITLE
fix: netbsd - uname requires arg in 3.8.0

### PR DESCRIPTION
**Pull request by YOU54F**
Building for `x86_64-unknown-netbsd` results in an error after upgrading os_info to 3.8.0

```
error[E0061]: this function takes 1 argument but 0 arguments were supplied
  --> /home/runner/.cargo/git/checkouts/os_info-2e057b05809a1ca6/83fc567/os_info/src/netbsd/mod.rs:10:19
   |
10 |     let version = uname()
   |                   ^^^^^-- an argument of type `&str` is missing
   |
note: function defined here
  --> /home/runner/.cargo/git/checkouts/os_info-2e057b05809a1ca6/83fc567/os_info/src/uname.rs:5:8
   |
5  | pub fn uname(arg: &str) -> Option<String> {
   |        ^^^^^ ---------
help: provide the argument
   |
10 |     let version = uname(/* &str */)
   |                        ~~~~~~~~~~~~
```

### CODE REVIEW

**Review by stanislav-tkach — APPROVED** [review]
Thank you for the pull request!

**Comment by zanchey** [comment]
I think this is wrong; netbsd's `uname` doesn't have a `-o` option.

**Comment by YOU54F** [comment]
doh. you are correct

https://man.netbsd.org/uname.1

think `-v` should work

you can try in a patch and use that in your build to check it works
